<?php
/**
 * @var \Laminas\Form\Form $form
 */
$this->htmlElement('body')->appendAttribute('class', 'watermarker add-set');
$this->headLink()->prependStylesheet($this->assetUrl('css/watermarker.css', 'Watermarker'));
$this->headScript()->appendFile($this->assetUrl('js/watermarker.js', 'Watermarker'));
$form->prepare();
?>

<?php echo $this->pageTitle($this->translate('Add Watermark Set'), 1, $this->translate('Watermarker')); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/watermarker'), ['class' => 'button']); ?>
</div>

<p class="explanation">
    <?php echo $this->translate('First, create a new watermark set with a name and settings. After saving, you will be able to add watermark images to the set.'); ?>
</p>

<?php echo $this->form()->openTag($form); ?>
<div id="page-content">
    <?php echo $this->formHidden($form->get('csrf')); ?>
    <div class="field">
        <div class="field-meta">
            <?php echo $this->formLabel($form->get('name')); ?>
            <div class="field-description"><?php echo $this->translate('Name for this watermark set.'); ?></div>
        </div>
        <div class="inputs">
            <?php echo $this->formInput($form->get('name')); ?>
        </div>
    </div>

    <div class="field">
        <div class="field-meta">
            <?php echo $this->formLabel($form->get('is_default')); ?>
            <div class="field-description"><?php echo $this->translate('Check to make this the default watermark set. Only one set can be default.'); ?></div>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($form->get('is_default')); ?>
        </div>
    </div>

    <div class="field">
        <div class="field-meta">
            <?php echo $this->formLabel($form->get('enabled')); ?>
            <div class="field-description"><?php echo $this->translate('Check to enable this watermark set.'); ?></div>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($form->get('enabled')); ?>
        </div>
    </div>
</div>
<div class="page-actions">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>