<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Watermarker\Form\ConfigForm $form
 */
$this->htmlElement('body')->appendAttribute('class', 'watermarker config');
$this->headLink()->prependStylesheet($this->assetUrl('css/watermarker.css', 'Watermarker'));
$form->prepare();
?>

<?php echo $this->pageTitle($this->translate('Watermarker Configuration'), 1, $this->translate('Media Watermarking')); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button type="submit"><?php echo $this->translate('Save'); ?></button>
</div>

<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag(); ?>