<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Watermarker\Form\WatermarkForm $form
 * @var array $watermark
 */
$this->htmlElement('body')->appendAttribute('class', 'watermarker edit');
$this->headLink()->prependStylesheet($this->assetUrl('css/watermarker.css', 'Watermarker'));
$this->headScript()->appendFile($this->assetUrl('js/watermarker.js', 'Watermarker'));
$form->prepare();
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle(sprintf($this->translate('Edit Watermark: "%s"'), $escape($watermark['name'])), 1, $this->translate('Media Watermarking')); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button type="submit"><?php echo $this->translate('Save'); ?></button>
</div>

<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag(); ?>